web:
  build: apache
  links:
    - elasticsearch:elasticsearch
    - mysql:mysql
  ports:
    - "8080:80"
  env_file: .env

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  container_name: elasticsearch563
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
  ulimits:
    memlock:
      soft: -1
      hard: -1
  mem_limit: 1g
  ports:
    - "9200:9200"
    - "9300:9300"
  env_file: .env

mysql:
  image: mysql:5.7
  env_file: .env
  